#Ordinal variables are categorical variable in which categories can be meaningfully ordered 
>like ex: rating of product grade a,b,c,d


#nominal variables is same like ordinal variable but there is nothing that indicates an intrinsic order of labels and in
principle
>like ex: all labels are equla no order like example color:red , green ,pink

In [2]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
pd.set_option("display.max_columns",None)  #it show all columns 
pd.set_option("display.max_rows",None)

In [6]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
df.value_counts()

Series([], dtype: int64)

In [8]:
df2=df[["KitchenQual","BldgType"]]

In [9]:
df2.head(4)

  KitchenQual BldgType
0          Gd     1Fam
1          TA     1Fam
2          Gd     1Fam
3          Gd     1Fam

In [10]:
le=LabelEncoder()

In [11]:
le.fit_transform(df2['BldgType'])

array([0, 0, 0, ..., 0, 0, 0])

In [12]:
df2["BldgType_L_enc"]=le.fit_transform(df2['BldgType'])  #label encoding transform variables into number form 
df2.head(6)

C:\Users\qavia\AppData\Local\Temp\ipykernel_22636\3252235510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["BldgType_L_enc"]=le.fit_transform(df2['BldgType'])  #label encoding transform variables into number form

  KitchenQual BldgType  BldgType_L_enc
0          Gd     1Fam               0
1          TA     1Fam               0
2          Gd     1Fam               0
3          Gd     1Fam               0
4          Gd     1Fam               0
5          TA     1Fam               0

In [13]:
df['BldgType'].value_counts()

1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

In [14]:
df["KitchenQual"].value_counts()

TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

In [15]:
# ex -excellent 
# gd good 
# ta typical /average 
# fa fair

In [16]:
order_Label={"Ex":4,"Gd":3,"TA":2,"Fa":1}

In [17]:
df2["KitchenQual_org_enc"] = df2['KitchenQual'].map(order_Label)

C:\Users\qavia\AppData\Local\Temp\ipykernel_22636\1514992020.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["KitchenQual_org_enc"] = df2['KitchenQual'].map(order_Label)

In [18]:
df2.head(10)

  KitchenQual BldgType  BldgType_L_enc  KitchenQual_org_enc
0          Gd     1Fam               0                    3
1          TA     1Fam               0                    2
2          Gd     1Fam               0                    3
3          Gd     1Fam               0                    3
4          Gd     1Fam               0                    3
5          TA     1Fam               0                    2
6          Gd     1Fam               0                    3
7          TA     1Fam               0                    2
8          TA     1Fam               0                    2
9          TA   2fmCon               1                    2

# Feature Scaling

#feature scaling is method to scale numeric features in the same scale or range(1 to 1 , 0to 1)
#this step involved in data preprocessing and before ml model training 
#it is also called as data normalization 
#we apply feature scaling on independent variables 
we fit feature scaling with train data and transform on train and test data 
#the scale of raw feature is differnet according to its units 
machine learning algo can't understand features units , understand only numbers

#ml algo required feature scaling 
those algo calculate distance 
knn 
k-means
support vector machine svm 
pcs principal component analysis 
linear disciminant analysis



#gradient descent based algo 
linear regression 
logistic regression 
neural network 


#tree based alg 
decisiontree 
random forest 
xgboost

# types of feature scaling 
min max scaler 
standard scaler 
max abs scaler 
robust scaler 
quantile transformer scaler 
power transformer scaler 
unit vector scaler